package com.telynet.viewExamples.Util;

import com.telynet.viewExamples.Model.Product;
import com.telynet.viewExamples.R;

import java.util.LinkedList;
import java.util.List;

public class ProductSimulator {
    public ProductSimulator(){};

    public List<Product> createProductoList() {
        List<Product> productsList = new LinkedList<>();
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));
        productsList.add(new Product("Fanta botella 1 lt", "4000030", R.mipmap.fanta_botella_foreground));
        productsList.add(new Product("Coca lata", "4000031", R.mipmap.coca_lata_foreground));
        productsList.add(new Product("Sprite botella 1 lt", "4000032", R.mipmap.sprite_botella_foreground));
        productsList.add(new Product("Coca Botella light", "4000033", R.mipmap.coca_botella_light_foreground));
        productsList.add(new Product("Coca Botellita", "4000034", R.mipmap.coca_botellita_foreground));
        productsList.add(new Product("Refresco botella 1 lt", "4000035", R.mipmap.refresco_litro_foreground));
        productsList.add(new Product("Soda lata", "4000036", R.mipmap.soda_lata_foreground));

        return productsList;
    }
}
